export const TEAMS: readonly string[] = [
  "Conquerors Cricket Club",
  "Warriors",
  "Unpredictables",
  "EV-Avengers",
  "Sentinels",
  "Wildcats",
  "Keystone Strikers",
  "Thunderbolts",
  "Old Monks",
  "Jalsa CC",
  "Royal Cheetahs",
  "Valley Forge XI",
  "Ex-town Hunters",
  "Super Eagles",
  "Chester Cheetahs",
  "Slammers",
  "KOP Mustangs",
  "D Khiladis",
  "Titans",
  "Bravehearts",
  "Rising Lions",
  "CSK Warriors",
  "Lethal Lansdale",
  "Gladiators",
  "Masters Cricket Club",
  "Mavericks",
  "Vikings",
  "Collegeville Super Kings",
  "Bulls",
  "Philly Spartans",
  "Eagles",
  "Steel Balls",
  "Hit and Run",
  "FIGHTERS-XI",
  "Jaguars",
  "Street Lions",
  "Stumperz",
  "Elite Eleven",
  "Volcanoes",
  "Falcons",
  "Philly Mawale",
  "KGF Warriors",
  "Wild Wolves",
  "Raptors",
  "Predictables",
  "Wayne Warriors",
  "Super Strikers",
  "Philly Chargers",
  "D'Town 11",
  "Avengers",
  "Lancers",
  "Yoddhas",
  "Red Lions",
  "Blade Runners",
  "AIB",
  "Roaring Lions",
] as const;
